package de.broscode.wsv.domain.arzt;

public enum ArztArt {
	ALLGEMEINMEDIZINER, 
	NEUROLOGE, 
	ZAHNARZT, 
	AUGENARZT, 
	UROLOGE, 
	GYNEKOLOGE, 
	HALS_NASEN_OHREN_ARZT, 
	LUNGENARZT, 
	RADIOLOGE, 
	KRANKENHAUS, 
	HAUSARZT, 
	ORTHOPAEDE, 
	SONDERFORM, 
	INTERNIST;
}
